### ISSUE TITLE
NNMF intialization

### ISSUE THREAD

**Issue by ahwillia** [madeleineudell/LowRankModels.jl#19]
I was looking into implementing Nonnegative Double Singular Value Decomposition (NNDSVD) to initialize NNMF problems. There is already an implementation of this in [NMF.jl](https://github.com/JuliaStats/NMF.jl), which we could follow very closely.

My only hesitation is that I'm not exactly sure how this would apply to a table with mixed data types. For the SVD initialization, we first normalize each column of A to have zero mean and unit variance... But this wouldn't be ideal if the data are meant to be strictly positive. Maybe we can just apply NNDSVD without any normalization?

**Comment by madeleineudell** [comment]
It would be great to implement NNDSVD. You might also want to take a look
at [this paper](http://arxiv.org/abs/1411.7245), which considers a variety
of other initializations.

You're right that normalizing `A` before applying a NNMF initialization
(probably) doesn't make sense. On the other hand, a multiplicative scaling
of the columns would not ruin the nonnegative structure, and can be applied
before an initialization. You could just grab that scaling from the
`.scale` attribute of the loss functions. If all loss functions have scale
1 then you need not use any normalization at all.

On Sun, Jul 5, 2015 at 10:01 PM, Alex Williams <notifications@github.com>
wrote:

> I was looking into implementing Nonnegative Double Singular Value
> Decomposition (NNDSVD) to initialize NNMF problems. There is already an
> implementation of this in NMF.jl <https://github.com/JuliaStats/NMF.jl>,
> which we could follow very closely.
>
> My only hesitation is that I'm not exactly sure how this would apply to a
> table with mixed data types. For the SVD initialization, we first normalize
> each column of A to have zero mean and unit variance... But this wouldn't
> be ideal if the data are meant to be strictly positive. Maybe we can just
> apply NNDSVD without any normalization?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/19>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by madeleineudell** [comment]
closed by #24
