### ISSUE TITLE
Load error with v0.4

### ISSUE THREAD

**Issue by ahwillia** [madeleineudell/LowRankModels.jl#26]
So I tried upgrading to `v0.4` and I've been having trouble loading the package.

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6354 (2015-07-29 14:17 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit d7351cf (0 days old master)
|__/                   |  x86_64-apple-darwin14.3.0

julia> using LowRankModels
ERROR: LoadError: LoadError: TypeError: apply_type: in Array, expected Type{T}, got Tuple{DataType,DataType}
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in include at ./boot.jl:254
 in include_from_node1 at ./loading.jl:197
 in require at ./loading.jl:146
while loading /Users/alex/.julia/v0.4/LowRankModels/src/glrm.jl, in expression starting on line 60
while loading /Users/alex/.julia/v0.4/LowRankModels/src/LowRankModels.jl, in expression starting on line 18
```

The issue relates to the argument list for `find_observations()`. In v0.4, this doesn't work:

```julia
julia> function test(obs::Array{(Int,Int),1})
       end
ERROR: TypeError: apply_type: in Array, expected Type{T}, got Tuple{DataType,DataType}
```

But this does:

```julia
julia> function test(obs::Array{Tuple{Int,Int},1})
       end
test (generic function with 1 method)
```

However, this second option doesn't seem to work with v0.3 so fixing this would create a compatibility issue.

As a sidenote... I decided to upgrade to 0.4 in the first place because I was having trouble using the `fit!` function in 0.3 -- I think the `func(;kwargs...)` syntax in 0.3 doesn't create a dictionary of keyword args, leading to the following error.

```julia
>> fit!(glrm)
ERROR: `keys` has no method matching keys(::Array{Any,1})
 in fit! at /Users/alex/.julia/v0.3/LowRankModels/src/fit.jl:11
```

It seems like it might be too much work to keep supporting compatibility with `v0.3`? But I don't know the timeline for the release of 0.4

**Comment by madeleineudell** [comment]
In general I hope to maintain .3 and .4 compatibility for everything except
parallelism; on parallel matters I make no guarantees (yet).

I fixed the problem on .3; it turns out that's not a compatibility issue
but just a type. (You would have found the problem on .4, too.)

The tuple type issue on .4 is also easy to fix, and I've fixed it: you can
just use @compat from the Compat package.

But there is another .4 error I don't yet know how to fix:
```
~/.julia/v0.3/LowRankModels (master ✘)✹✭ ᐅ julia examples/simple_glrms.jl
simple glrm examples
ERROR: LoadError: MethodError: `length` has no method matching
length(::LowRankModels.quadratic)
 in call at /Users/madeleine/.julia/v0.4/LowRankModels/src/glrm.jl:20
 in call at /Users/madeleine/.julia/v0.4/LowRankModels/src/glrm.jl:26
 in call at /Users/madeleine/.julia/v0.4/LowRankModels/src/glrm.jl:34
 in fit_pca at
/Users/madeleine/.julia/v0.3/LowRankModels/examples/simple_glrms.jl:12
 in include at ./boot.jl:254
 in include_from_node1 at loading.jl:133
 in process_options at ./client.jl:305
 in _start at ./client.jl:405
while loading
/Users/madeleine/.julia/v0.3/LowRankModels/examples/simple_glrms.jl, in
expression starting on line 88
```
I can't tell where length(::quadratic) is being called; I agree if it's
happening it *would* be a method error. Any ideas?

On Wed, Jul 29, 2015 at 12:37 PM, Alex Williams <notifications@github.com>
wrote:

> So I tried upgrading to v0.4 and I've been having trouble loading the
> package.
>
>                _
>    _       _ _(_)_     |  A fresh approach to technical computing
>   (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
>    _ _   _| |_  __ _   |  Type "help()" for help.
>   | | | | | | |/ _` |  |
>   | | |_| | | | (_| |  |  Version 0.4.0-dev+6354 (2015-07-29 14:17 UTC)
>  _/ |\__'_|_|_|\__'_|  |  Commit d7351cf (0 days old master)
> |__/                   |  x86_64-apple-darwin14.3.0
>
> julia> using LowRankModels
> ERROR: LoadError: LoadError: TypeError: apply_type: in Array, expected Type{T}, got Tuple{DataType,DataType}
>  in include at ./boot.jl:254
>  in include_from_node1 at ./loading.jl:197
>  in include at ./boot.jl:254
>  in include_from_node1 at ./loading.jl:197
>  in require at ./loading.jl:146
> while loading /Users/alex/.julia/v0.4/LowRankModels/src/glrm.jl, in expression starting on line 60
> while loading /Users/alex/.julia/v0.4/LowRankModels/src/LowRankModels.jl, in expression starting on line 18
>
> The issue relates to the argument list for find_observations(). In v0.4,
> this doesn't work:
>
> julia> function test(obs::Array{(Int,Int),1})
>        end
> ERROR: TypeError: apply_type: in Array, expected Type{T}, got Tuple{DataType,DataType}
>
> But this does:
>
> julia> function test(obs::Array{Tuple{Int,Int},1})
>        end
> test (generic function with 1 method)
>
> However, this second option doesn't seem to work with v0.3 so fixing this
> would create a compatibility issue.
>
> As a sidenote... I decided to upgrade to 0.4 in the first place because I
> was having trouble using the fit! function in 0.3 -- I think the
> func(;kwargs...) syntax in 0.3 doesn't create a dictionary of keyword
> args, leading to the following error.
>
> >> fit!(glrm)
> ERROR: `keys` has no method matching keys(::Array{Any,1})
>  in fit! at /Users/alex/.julia/v0.3/LowRankModels/src/fit.jl:11
>
> It seems like it might be too much work to keep supporting compatibility
> with v0.3? But I don't know the timeline for the release of 0.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/26>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by ahwillia** [comment]
I can't reproduce this `length` error on my machine. If you do `git pull && make` to update julia do you still get the problem?

**Comment by madeleineudell** [comment]
When I try to make julia I get error 2 (usually, and currently). Hence my
tendency to stick with releases... But glad to know the error is fixed on
julia master.

On Thu, Jul 30, 2015 at 11:34 AM, Alex Williams <notifications@github.com>
wrote:

> I can't reproduce this length error on my machine. If you do git pull &&
> make to update julia do you still get the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/26#issuecomment-126427120>
> .
>



-- 
Madeleine Udell
www.stanford.edu/~udell

**Comment by ahwillia** [comment]
Closing this because the original problems are fixed by https://github.com/madeleineudell/LowRankModels.jl/commit/7f591efda77d341514f326164224d732a5c60c2e and https://github.com/madeleineudell/LowRankModels.jl/commit/872c21b87934e25b0a2fea0424371a5779e25c40
