### ISSUE TITLE
init_svd! fails for rank-one model

### ISSUE THREAD

**Issue by ahwillia** [madeleineudell/LowRankModels.jl#28]
Minor issue I happened to come across. I might try to chase this down this afternoon.

```julia
using LowRankModels

m = 100
n = 100
k = 1 # changing k to be 2 or 3 fixes this

A = randn(m,k)*randn(k,n)
loss = quadratic()
r = zeroreg()
glrm = GLRM(A,loss,r,r,k)
init_svd!(glrm)
```

Produces an error:

```julia
ERROR: DimensionMismatch("*")
 in gemm_wrapper! at linalg/matmul.jl:270
 in A_mul_Bt at linalg/matmul.jl:141
 in A_mul_Bc at linalg/matmul.jl:172
 in init_svd! at /Users/alex/.julia/v0.3/LowRankModels/src/initialize.jl:74
```

This seems to only be an issue for rank-one models (changing `k` to be 2 or 3 fixes it).

**Comment by ahwillia** [comment]
So this is essentially occurring because `k` is decremented and becomes zero on this line: https://github.com/madeleineudell/LowRankModels.jl/blob/master/src/initialize.jl#L53

Seems like a subjective call on how to fix this. Maybe leave the code as is, but throw an error when `k=0` telling the user to set `offset=false` to initialize a rank-one model with demeaned data.

**Comment by madeleineudell** [comment]
Yes, I think a warning would be the right thing here. Thanks for catching
that.
