### ISSUE TITLE
shareglrm doesn't play nice with fit_dataframe

### ISSUE THREAD

**Issue by alejandroschuler** [madeleineudell/LowRankModels.jl#4]
shareglrm wants ry to be a single regularizer function, whereas fit_dataframe expects use of glrm, which assumes ry::Array{Regularizer,1} and thus equilibrate_variance and offset don't work with shareglrm

**Comment by alejandroschuler** [comment]
btw I've addressed this in my pull request

**Comment by madeleineudell** [comment]
closed by PR #5
