### ISSUE TITLE
Working with the "psych" Rdataset and converting NaN to NA in a dataframe

### ISSUE THREAD

**Issue by NandanaSengupta** [madeleineudell/LowRankModels.jl#45]
Hi, 

Just wanted to let you know that the basic example in the README file is not working right now because of the presence of NaN values. Currently running

import RDatasets
df = RDatasets.dataset("psych", "msq")
glrm, labels = GLRM(df,2)

returns the error "ERROR: Observed value in entry (1, 9) is NaN."

It would be useful to have an option in the GLRM command to treat NaN as NA. In the absence of that could you let me know how to convert NaN values to NA in a Julia DataFrame? It seems to  be a non-trivial problem (I (unsuccessfully) tried many variants of "df[isnan(df)] = NA" ).

Thanks!
Nandana

**Comment by madeleineudell** [comment]
Sure! Just preprocess the data frame with `NaNs_to_NAs!(df)` or call `GLRM(df, 2; NaNs_to_NAs = true)`. I've changed the example to use the latter option,  and updated the README.

**Comment by NandanaSengupta** [comment]
Great thanks! I did manage to code the NaNs to NAs -- but my code wasn't general, so this helps a lot.
