### ISSUE TITLE
documentation needs update / OrdinalHinge constructor

### ISSUE THREAD

**Issue by mravanba** [madeleineudell/LowRankModels.jl#49]
1) In the losses.jl, LogisticLoss is called LogLoss, which is inconsistent with the documentation.
2) Using OrdinalHinge loss will raise an error, because it does not define an empty constructor, needed by the copy method in utilities.

**Comment by ahwillia** [comment]
My preference would be for LogisticLoss over LogLoss as this is consistent
with what is in EmpiricalRisks.jl and doesn't have the possibility of
getting confused with the log function (e.g. as a canonical link for
Poisson)

**Comment by madeleineudell** [comment]
Yes, I also prefer the `LogisticLoss` as a name. But where in losses.jl do you see `LogLoss` used?

**Comment by madeleineudell** [comment]
(I've fixed the other error you point out in the most recent commit.)

**Comment by mravanba** [comment]
hmm... you're right about the LogLoss. My local version was not up to date.
