### ISSUE TITLE
High GC (with shareglrm)

### ISSUE THREAD

**Issue by alejandroschuler** [madeleineudell/LowRankModels.jl#6]
Hey, I'm getting some runtimes (using @time) of the parallelized version of fit!() that look like this:
(1000 observations of 550 features)
elapsed time: 12.81354915 seconds (592596512 bytes allocated, 5.76% gc time)

(10000 observations of 550 features)
elapsed time: 42.705608708 seconds (2916525292 bytes allocated, 42.89% gc time)

(50000 observations of 550 features)
elapsed time: 160.638440166 seconds (11031343640 bytes allocated, 51.76% gc time)

(100000 observations of 550 features)
elapsed time: 1421.327476493 seconds (32386723552 bytes allocated, 88.19% gc time)

This is using a machine with 10 processors.

Also, when I look at top, I see that the grand majority of the time the process is only running on one CPU. Every now and again I'll see the parallelization (suddenly multiple julia processes all taking ~100% CPU), but then it all goes back to the single CPU. This happens less frequently when I'm running on the larger dataset, which could be reflective of the same thing I'm seeing with the gc time.

This doesn't happen with the serial implementation. 

(10000 observations of 550 features)
obj went up to 8.760023035973597e6; reducing step size to 0.7000000000000001
obj went up to 8.1832688405943755e6; reducing step size to 0.46666666666666673
obj went up to 7.83172884385661e6; reducing step size to 0.31111111111111117
obj went up to 7.611766313323507e6; reducing step size to 0.15555555555555559
obj went up to 7.403213032260401e6; reducing step size to 0.051851851851851864
obj went up to 7.270450432882523e6; reducing step size to 0.012962962962962966
obj went up to 7.221932865355106e6; reducing step size to 0.0025925925925925934
elapsed time: 88.786999616 seconds (12047987036 bytes allocated, 9.12% gc time)

**Comment by alejandroschuler** [comment]
Looks like optimizing the shareglrm code fixed the high gc time! This is a new result:

(100000 observations of 550 features)
elapsed time: 210.163523154 seconds (39530820612 bytes allocated, 11.12% gc time)

**Comment by madeleineudell** [comment]
That's fantastic!

On Sun, May 31, 2015 at 11:08 AM, Alejandro Schuler <
notifications@github.com> wrote:

> Looks like optimizing the shareglrm code fixed the high gc time! This is a
> new result:
>
> (100000 observations of 550 features)
> elapsed time: 210.163523154 seconds (39530820612 bytes allocated, 11.12%
> gc time)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/6#issuecomment-107230041>
> .
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell
