### ISSUE TITLE
How to run distributely?

### ISSUE THREAD

**Issue by Tagar** [madeleineudell/LowRankModels.jl#88]
Sorry for a newbie question.. is there is a way to run this distributively? 

For example, in Hadoop, or on Spark or in other distributed frameworks?

Thanks.

**Comment by Tagar** [comment]
Posted a question on stats.stackexchange.com: 
https://stats.stackexchange.com/questions/355260/distributed-pca-or-an-equivalent

**Comment by madeleineudell** [comment]
No, this package does not enable distributed optimization. If you need a distributed implementation, take a look at the H2O implementation: http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/glrm.html
