### ISSUE TITLE
A non linear GLRM is good for visualization?

### ISSUE THREAD

**Issue by RaulRomaniF** [madeleineudell/LowRankModels.jl#89]
With nonlinear GLRM I mean to use a multilayer perceptron to solve for X and Y in an alternating minimization fashion. With visualization I mean dimensionality reduction to 2D.

I think a nonlinear GLRM would improve the reconstruction, but do you think it will also improve the low dimensional representations "X variable"?. 

What kind of model (i.e. losses and regularizations) do you think it would be good for visualization.

**Comment by madeleineudell** [comment]
This package only implements (bi)linear models. If you want something that's designed for visualization, try t-SNE?
