### ISSUE TITLE
shareglrm `fit!` recomputes X*Y

### ISSUE THREAD

**Issue by alejandroschuler** [madeleineudell/LowRankModels.jl#9]
In the X update:
```
...
@everywhere begin
            # X update
            gemm!('T','N',1.0,X[:,xlcols],Y.s,0.0,XYX)
...
```

And then again in the objective evaluation:
```
...
# evaluate objective 
        obj[1] = 0
        @everywhere begin
            XY = X[:,xlcols]'*Y
...
```
I see that this second computation has to be done because by the time the objective is computed, X and Y have changed. On the other hand, I don't see why we can't omit the first calculation and just do the second one, holding that value of XY over into the next iteration of the X update. We can add a pre-computation of XY into the initialization block so that it doesn't choke the first time around. 

Also, why is `gemm!` used in the X update, but not in the objective eval? Shouldn't `gemm!` be faster for both?

**Comment by madeleineudell** [comment]
Yes, these are great suggestions! They'll make the code a bit more
complicated, but should provide some speedup.

In fact, the computation `XY = X[:,xlcols]'*Y` in the evaluation of the
objective is the only place where I see memory allocation going on in each
iteration; it's possible that by replacing this by an operation that
doesn't allocate memory (eg `gemm!`) we could reduce the big hit we're
seeing on GC time.

On Fri, May 29, 2015 at 3:41 PM, Alejandro Schuler <notifications@github.com
> wrote:

> In the X update:
>
> ...
> @everywhere begin
>             # X update
>             gemm!('T','N',1.0,X[:,xlcols],Y.s,0.0,XYX)
> ...
>
> And then again in the objective evaluation:
>
> ...
> # evaluate objective
>         obj[1] = 0
>         @everywhere begin
>             XY = X[:,xlcols]'*Y
> ...
>
> I see that this second computation has to be done because by the time the
> objective is computed, X and Y have changed. On the other hand, I don't see
> why we can't omit the first calculation and just do the second one, holding
> that value of XY over into the next iteration of the X update. We can add a
> pre-computation of XY into the initialization block so that it doesn't
> choke the first time around.
>
> Also, why is gemm! used in the X update, but not in the objective eval?
> Shouldn't gemm! be faster for both?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/madeleineudell/LowRankModels.jl/issues/9>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by alejandroschuler** [comment]
Alright, I've addressed that in my latest commit, I'll send a PR

**Comment by alejandroschuler** [comment]
Resolved in my latest commit, along with high gc issue.
