### ISSUE TITLE
What Julia version is this package compatible for?

### ISSUE THREAD

**Issue by shashins** [madeleineudell/LowRankModels.jl#90]
I am trying to install this package on Julia 1.1 and getting error messages.

**Comment by cianodonnell** [comment]
I too would be interested in an updated version compatible with Julia 1.1 if it were available.

**Comment by baggepinnen** [comment]
I managed to get some stuff running on my fork
https://github.com/baggepinnen/LowRankModels.jl
you can try to install it and see if you get it off the ground

**Comment by madeleineudell** [comment]
v1.0.0 (and the master branch) now work on Julia 1.0+. Let me know if you run into any errors!
